INSERT INTO recipes
(id, name, type, requires_appliance, avg_cost, protein, calories)
VALUES

(gen_random_uuid(), 'Pistachio chicken', 'HOME_COOKED', true, 180, 28, 520),
(gen_random_uuid(), 'Tangy Fried Okra', 'HOME_COOKED', true, 80, 5, 220),
(gen_random_uuid(), 'Healthy Chicken Korma', 'HOME_COOKED', true, 190, 30, 550),
(gen_random_uuid(), 'Brown Lentil Dhal', 'HOME_COOKED', true, 70, 12, 320),
(gen_random_uuid(), 'Thari Wala Chicken', 'HOME_COOKED', true, 170, 27, 500),
(gen_random_uuid(), 'Chickpea Masala', 'HOME_COOKED', true, 75, 14, 340),
(gen_random_uuid(), 'Palak Paneer', 'HOME_COOKED', true, 140, 18, 420),
(gen_random_uuid(), 'Baingan Bharta', 'HOME_COOKED', true, 70, 4, 210),
(gen_random_uuid(), 'Vegetable Pulao', 'HOME_COOKED', true, 90, 8, 390),
(gen_random_uuid(), 'Chicken Tikka Masala', 'HOME_COOKED', true, 200, 32, 580),
(gen_random_uuid(), 'Rajma Curry', 'HOME_COOKED', true, 80, 15, 360),
(gen_random_uuid(), 'Aloo Gobi', 'HOME_COOKED', true, 65, 4, 240),
(gen_random_uuid(), 'Matar Paneer', 'HOME_COOKED', true, 150, 20, 460),
(gen_random_uuid(), 'Egg Curry', 'HOME_COOKED', true, 110, 22, 410),
(gen_random_uuid(), 'Chicken Biryani', 'HOME_COOKED', true, 220, 35, 700),
(gen_random_uuid(), 'Vegetable Biryani', 'HOME_COOKED', true, 120, 9, 520),
(gen_random_uuid(), 'Masoor Dal', 'HOME_COOKED', true, 70, 13, 330),
(gen_random_uuid(), 'Chana Dal', 'HOME_COOKED', true, 75, 12, 310),
(gen_random_uuid(), 'Paneer Butter Masala', 'HOME_COOKED', true, 160, 22, 550),
(gen_random_uuid(), 'Chicken Curry', 'HOME_COOKED', true, 170, 28, 500),
(gen_random_uuid(), 'Lemon Rice', 'HOME_COOKED', true, 60, 5, 300),
(gen_random_uuid(), 'Cabbage Sabzi', 'HOME_COOKED', true, 60, 3, 180),
(gen_random_uuid(), 'Fish Curry', 'HOME_COOKED', true, 200, 30, 520),
(gen_random_uuid(), 'Vegetable Curry', 'HOME_COOKED', true, 75, 6, 260),
(gen_random_uuid(), 'Paneer Bhurji', 'HOME_COOKED', true, 140, 21, 430),
(gen_random_uuid(), 'Dal Tadka', 'HOME_COOKED', true, 80, 14, 350),
(gen_random_uuid(), 'Chicken Keema', 'HOME_COOKED', true, 190, 32, 540),
(gen_random_uuid(), 'Bhindi Masala', 'HOME_COOKED', true, 75, 5, 230),
(gen_random_uuid(), 'Vegetable Khichdi', 'HOME_COOKED', true, 70, 9, 320),
(gen_random_uuid(), 'Paneer Tikka', 'HOME_COOKED', true, 160, 24, 480),
(gen_random_uuid(), 'Egg Bhurji', 'HOME_COOKED', true, 90, 20, 380),
(gen_random_uuid(), 'Chicken Soup', 'HOME_COOKED', true, 120, 18, 240),
(gen_random_uuid(), 'Tomato Soup', 'HOME_COOKED', true, 60, 3, 150),
(gen_random_uuid(), 'Mixed Vegetable Sabzi', 'HOME_COOKED', true, 75, 6, 250),
(gen_random_uuid(), 'Kadai Paneer', 'HOME_COOKED', true, 150, 22, 470),
(gen_random_uuid(), 'Butter Chicken', 'HOME_COOKED', true, 220, 34, 620),
(gen_random_uuid(), 'Tandoori Chicken', 'HOME_COOKED', true, 200, 36, 580),
(gen_random_uuid(), 'Vegetable Upma', 'HOME_COOKED', true, 60, 7, 280),
(gen_random_uuid(), 'Poha', 'HOME_COOKED', true, 50, 6, 250),
(gen_random_uuid(), 'Oats Khichdi', 'HOME_COOKED', true, 70, 8, 300),
(gen_random_uuid(), 'Sprouts Curry', 'HOME_COOKED', true, 75, 14, 330),
(gen_random_uuid(), 'Paneer Paratha', 'HOME_COOKED', true, 100, 15, 420),
(gen_random_uuid(), 'Chicken Stew', 'HOME_COOKED', true, 170, 28, 480),
(gen_random_uuid(), 'Vegetable Stew', 'HOME_COOKED', true, 80, 6, 260),
(gen_random_uuid(), 'Mushroom Masala', 'HOME_COOKED', true, 120, 8, 300),
(gen_random_uuid(), 'Soybean Curry', 'HOME_COOKED', true, 85, 20, 390),
(gen_random_uuid(), 'Chicken Fried Rice', 'HOME_COOKED', true, 180, 25, 600),
(gen_random_uuid(), 'Vegetable Fried Rice', 'HOME_COOKED', true, 110, 8, 520),
(gen_random_uuid(), 'Moong Dal', 'HOME_COOKED', true, 70, 13, 310);